apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-go-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world-go-app
  template:
    metadata:
      labels:
        app: hello-world-go-app
    spec:
      containers:
      - image: helloworld:fea3a76
        imagePullPolicy: Never
        name: helloworld-go-app
        ports:
        - containerPort: 3000
