apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-go-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world-go-app
  template:
    metadata:
      labels:
        app: hello-world-go-app
    spec:
      containers:
      - name:  helloworld-go-app
        image: helloworld
        imagePullPolicy: Never
        ports:
        - containerPort: 3000  
